### ndarray를 이용할 때 주의점
1. ndarray의 데이터 수가 같더라도, 차원이 다르면 전혀 다른 ndarray이다.
	- 즉, 차원이 중요한 팩터다.
2. ndarray내의 원소는 문자열, 실수, 불 값 모두 가능하지만, 하나의 ndarray내의 원소들은 모두 동일한 데이터 타입을 가져야 한다.
	- 만약, `np.array()`를 이용해서 ndarray생성 시 인자에 서로 다른 타입을 가지는 원소가 들어오면, 더 큰 데이터 타입으로 형 변환을 일괄 적용한다.
	- `astype()`을 이용해서 ndarray의 원소의 타입을 일괄 변경할 수 있다. 보통, ndarray의 크기를 줄이기 위해서(양자화를 위해)사용한다.

## Practice 1 : ndarray생성 및 다양한 인스턴스 변수에 접근하기
- shape, ndim

In [ ]:
import numpy as np

array1 = np.array([[7, 8, 9], [10, 11, 12]])

print(array1)
print('array1 type : ', type(array1))
print('array1 shape : ', array1.shape)
print('array1 ndim : ', array1.ndim)

[[ 7  8  9]
 [10 11 12]]
array1 type :  <class 'numpy.ndarray'>
array1 shape :  (2, 3)
array1 ndim :  2
array1 dtype :  int64


### Practice 2 : ndarray의 원소 확인하기
- dtype

In [ ]:
import numpy as np

array2 = np.array([1, 1.0, 2])
print(array2)
print(array2.dtype)

print()


array3 = np.array(['a', 1.0, 2])
print(array3)
print(array3.dtype)


[1. 1. 2.]
float64

['a' '1.0' '2']
<U32


### Practice 3 : `astype()`를 이용해서 ndarray 원소의 타입 일괄 변경하기
- 메모리를 줄이기 위해서 float64 -> int32 등으로 변경하는 경우도 있음(양자화)
- `astype()`메서드는 원본 ndarray를 수정하는게 아니라, 자료형이 바뀐 새로운 ndarray를 반환한다.

In [ ]:
import numpy as np

list1 = [1, 2, 3]

array1 = np.array(list1)
print(array1)
print(array1.dtype)

print()

array2 = array1.astype('float64')
print(array2)
print(array2.dtype)


print()

array3 = array2.astype('int32')
print(array3)
print(array3.dtype)

[1 2 3]
int64

[1. 2. 3.]
float64
int64

[1 2 3]
int32


### Practice 4 : ndarray를 경우에 따라서 편하게 생성하기
1. `numpy.arange()`
	- `range()`와 유사한 방법으로 array만들기
	- 원소의 dtype은 int64이다.

2. `numpy.zeros()`, `numpy.ones()`
	- 인자는 원하는 Shape:Tuple을 받는다.
	- dtype을 인자로 적어주지 않으면, default는 float64이다.

In [ ]:
import numpy as np

array1 = np.arange(10)
print(array1)
print(array1.dtype, array1.shape)

array2 = np.arange(1, 10, 2)
print(array2)
print(array2.dtype, array2.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[1 3 5 7 9]


In [28]:
import numpy as np

array1 = np.zeros((1, 2))
print(array1)
print(array1.dtype, array1.shape)

print()

array2 = np.ones((1, 2))
print(array2)
print(array2.dtype, array2.shape)

[[0. 0.]]
float64 (1, 2)

[[1. 1.]]
float64 (1, 2)


### Practice 5 : `reshape()`을 이용해서 ndarray의 크기 및 차원 바꾸기
- -1을 이용하면, 차원 변환을 더 쉽게할 수 있다.
- (-1, 1)꼴로의 크기 변환은 stack(), concat()과 같이 ndarray를 이어 붙일 때 크기를 맞추는 경우 많이 사용된다.

In [33]:
import numpy as np

array1 = np.arange(10)
array2 = array1.reshape(2, 5)
array3 = array1.reshape(5, 2)
print(array1, array2, array3, sep='\n\n')


[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
