### Practice : `np.sort()`, `ndarray.sort()`, `argsort()`를 이용해 다양한 방식으로 sorting하기
- sort()함수는 기본적으로 오름차순 정렬을 수행한다.
1. `np.sort(ndarray)`
	- 인자로 들어온 ndarray를 수정하지 않는다. (Out of place 연산)
	- 반환값은 정렬된 새로운 ndarray이다.

2. `ndarray.sort()`
	- 원 ndarray 자체를 수정한다. (In place 연산)
	- 반환값은 None이다.

3. `np.argsort(ndarray)`
	- numpy의 ndarray는 pandas의 DataFrame과 다르게, 모든 행렬(혹은 텐서)의 각 행 혹은 열에 대한 정보를 가질 수 없다. 따라서, 실제 데이터와 축에 대한 정보를 가지는 ndarray를 각각 다루어야 하는데, 이런 경우 argsort가 위력을 발휘한다.

In [2]:
import numpy as np

org_array = np.array([3, 1, 5, 9])

print(org_array, end='\n\n')

sorted_array1 = np.sort(org_array)
print('original array : ', org_array)
print('sorted array : ', sorted_array1)

sorted_array2 = org_array.sort()
print('original array : ', org_array)
print('sorted array : ', sorted_array2)

[3 1 5 9]

original array :  [3 1 5 9]
sorted array :  [1 3 5 9]
original array :  [1 3 5 9]
sorted array :  None


- sort()는 기본적으로 오름차순이기 때문에, 내림차순을 수행하기 위해서 인덱싱을 통해 뒤집는다.
	- 인덱싱 수행 시 ::step의 형태에서 step이 양수이면 start:end:step의 형태가 되고, step이 음수이면 end:start:step의 형태가 된다.

In [3]:
import numpy as np

sorted_array_desc = np.sort(org_array)[::-1]
print(sorted_array_desc)

[9 5 3 1]


* ndim이 2 이상인 ndarray에 대해서 정렬을 수행하는 경우, axis를 지정해줌으로써, 원하는 정렬을 수행할 수 있다.

In [6]:
import numpy as np

array_2d = np.array([[8, 12], [7, 1]])

print(array_2d)

axis_0_sort = np.sort(array_2d, axis=0)
print(axis_0_sort)

axis_1_sort = np.sort(array_2d, axis=1)
print(axis_1_sort)

[[ 8 12]
 [ 7  1]]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


- 아래와 같이, 한 ndarray는 성적을, 또 다른 한 ndarray는 이름을 나타낼 때, `np.argsort()`가 유용하게 이용될 수 있다.

In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sorted_score = np.sort(score_array)
sorted_score_indices_asc = np.argsort(score_array)

print(f'sorted_score_indices_asc : {sorted_score_indices_asc}')

# 정렬된 이름과, 정렬된 점수를 얻을 수 있다.
print(name_array[sorted_score_indices_asc])
print(f'sorted_score : {sorted_score}')

sorted_score_indices_asc : [0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
sorted_score : [78 84 88 95 98]
